// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://byjeirimbkklgdxqcckm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ5amVpcmltYmtrbGdkeHFjY2ttIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM0MTAyNjMsImV4cCI6MjA2ODk4NjI2M30.lJCLaCQrttHuCEIQamsCbSPx6y69kJWMVaWnPUE7JF8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});